
- name: "Environment: {{ ambiente }}   Site: {{ sito }} - Query MSSQL Server"
  hosts: localhost
  connection: local
  gather_facts: false

  pre_tasks:

    - assert:
        that: item is defined
      with_items:
        - ambiente
        - sito

    - name: Loading {{ ambiente }} Environment Settings for Site {{ sito }}
      include_vars: 
        dir: vars/{{ ambiente }}/{{ sito }}
        depth: 1

    - set_fact:
        create_token: /api/v2/tokens/
        list_jobs: /api/v2/jobs/

  tasks:

#    - name: create Auth Token
#      uri:
#        url: "https://{{ awx_srv }}{{ create_token }}"
#        method: POST
#        user: "{{ awx_usr }}"
#        password: "{{ awx_pwd }}"
#        headers:
#          Accept: "application/json"
#          Content-Type: "application/json"
#          #Authorization: "{{key}}"
#        force_basic_auth: true
#        validate_certs: false
#        return_content: yes
#      register: uri_out
#      ignore_errors: true

    - name: List Jobs
      uri:
        url: "https://{{ awx_srv }}{{ list_jobs }}"
        method: GET
        headers:
          Accept: "application/json"
          Content-Type: "application/json"
          Authorization: "{{ awx_token }}"
        validate_certs: false
        return_content: yes
      register: jobs_out
      ignore_errors: true

    - debug:
        var: jobs_out
      when: jobs_out is defined


