- name: Just a Play
  hosts: all
  gather_facts: false

  tasks:

    - name: run something
      command: /bin/true
      #command: /bin/false
      register: a_run
#      ignore_errors: true
      delegate_to: localhost

#    - debug: var=a_run
#
#    - debug:
#        msg: Hello the Play failed
#      when: a_run.rc != 0
#      delegate_to: localhost
#
#    - debug:
#        msg: Hello the Play Succeeded
#      when: a_run.rc == 0
#      delegate_to: localhost

