
- name: "ISP {{ ambiente }} Environment DR Switch to {{ sito }} Site"
  hosts: localhost
  gather_facts: false

  pre_tasks:

    - assert:
        that: item is defined
      with_items:
        - ambiente
        - sito

    - name: Loading {{ ambiente }} Environment Settings for Site {{ sito }}
      include_vars: 
        dir: vars/{{ ambiente }}/{{ sito }}
        depth: 1

  tasks:

    - name: post URI
      uri:
        url: "{{ post_uri.uri }}"
        method: POST
        user: "{{ post_uri.usr }}"
        password: "{{ post_uri.pwd }}"
        force_basic_auth: yes
        return_content: yes
        validate_certs: no
        body_format: json
        body: '{"flowUuid":"e0a94276-3693-4695-988e-7c590124ec28"}' 
        status_code: 201
      register: postout

    - debug:
        var: postout

    - set_fact:
         post_result: "{{ postout.json }}"

    - debug:
        msg: "Post Result: {{ post_result }}"

    - name: get URI
      uri:
        url: "{{ rest_uri.uri }}"
        method: GET
        user: "{{ rest_uri.usr }}"
        password: "{{ rest_uri.pwd }}"
        force_basic_auth: yes
        return_content: yes
        validate_certs: no
        body_format: json
      register: getout

    - debug:
        var: getout

    - set_fact:
         getresult: "{{ getout.json | replace('[','') | replace(']','') }}"

    - debug:
        var: getresult

    - debug:
        var: getresult.executionId

