
- name: "ISP {{ ambiente }} Environment DR Switch to {{ sito }} Site"
  hosts: localhost
  gather_facts: false

  pre_tasks:

    - name: include {{ sito }} vars for environment {{ ambiente }}
      include_vars: 
        dir: vars/{{ ambiente }}/{{ sito }}
        depth: 1

    - name: load initial vmstate
      read_csv:
        path: /tmp/vminitial.csv
        fieldnames: vm,state,center
        delimiter: '|'
      register: vminitial 

    - set_fact:
        myinitial: "{{ myinitial | default([]) +  [{ 'name': item.vm, 'state': item.state, 'vcenter': item.center }] }}"
      with_items: "{{ vminitial.list | json_query('[*]') }}"

    - include_tasks: write2db.yml
      vars:
        db_name: "{{ db_server }}"
        db_operation: "insert start DR on site {{ sito }}"

  tasks:

    - name: vmware_control.yml
      include_tasks: vmware_control.yml


