
- name: "ISP {{ ambiente }} Environment DR Switch to {{ sito }} Site"
  hosts: localhost
  gather_facts: false

  pre_tasks:

    - name: include {{ sito }} vars for environment {{ ambiente }}
      include_vars: 
        dir: vars/{{ ambiente }}/{{ sito }}
        depth: 1

    - include_tasks: write2db.yml
      vars:
        db_name: "{{ db_server }}"
        db_operation: "insert start DR on site {{ sito }}"

  tasks:

    - name: calling controll block
      include_tasks: loop_control.yml


