
- name: "Checking Global Variables"
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    status_content: "{{ lookup('file','/isp_dr_data/status.txt') }}"

  tasks:

    - debug:
        msg: "ISP DIR Status: {{ status_content }}"

