
- name: "Checking Global Variables"
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    status_content: "{{ lookup('file','/isp_dr_data/status.json') }}"

  tasks:

    - debug:
        var: status_content

    - debug:
        msg: "VMWare: {{ status_content.systems['VMWare'].status }} - {{ status_content.systems['VMWare'].msg }}"

