
- name: "ISP {{ ambiente }} Environment DR Switch to {{ sito }} Site: Run Windows CMD"
  hosts: windows_servers
  gather_facts: false

  pre_tasks:

    - assert:
        that: item is defined
      with_items:
        - ambiente
        - sito
      run_once: true

    - name: Loading {{ ambiente }} Environment Settings for Site {{ sito }}
      include_vars: 
        dir: vars/{{ ambiente }}/{{ sito }}
        depth: 1
      run_once: true

  tasks:

    - name: test win servers
      win_command: whoami
      register: win_who

    - debug:
        var: win_who

