
- name: "Environment: {{ ambiente }} Site: {{ sito }} - Run Linux CMD"
  hosts: linux_servers
  gather_facts: false

  pre_tasks:

    - assert:
        that: item is defined
      with_items:
        - ambiente
        - sito
      run_once: true

    - name: Loading {{ ambiente }} Environment Settings for Site {{ sito }}
      include_vars: 
        dir: vars/{{ ambiente }}/{{ sito }}
        depth: 1
      run_once: true

  tasks:

    - name: write files
      shell: date +"%T.%N" > /tmp/ans_test_parallel_2.txt && sleep 120 && date +"%T.%N" >> /tmp/ans_test_parallel_2.txt
      register: lin_cmd

#    - debug:
#        var: lin_cmd

    - name: check  files
      shell: cat /tmp/ans_test_parallel_2.txt
      register: lin_result

    - debug:
        var: lin_result

#- name: "Environment: {{ ambiente }} Site: {{ sito }}"
#  hosts: localhost
#  gather_facts: false
#
#  pre_tasks:
#
#    - assert:
#        that: item is defined
#      with_items:
#        - ambiente
#        - sito
#      run_once: true
#      delegate_to: localhost
#
#    - name: Loading {{ ambiente }} Environment Settings for Site {{ sito }}
#      include_vars: 
#        dir: vars/{{ ambiente }}/{{ sito }}
#        depth: 1
#      run_once: true
#      delegate_to: localhost
#
#  tasks:
#
#    - name: write files
#      shell: date +"%T.%N" > /tmp/ans_test_parallel_2.txt && sleep 120 && date +"%T.%N" >> /tmp/ans_test_parallel_2.txt
##      async: 50
##      poll: 10
#      delegate_to: "{{ item }}"
#      loop: "{{ linux_servers }}"
#
