
- name: "Environment: {{ ambiente }}   Site: {{ sito }}"
  hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: false

  pre_tasks:

    - assert:
        that: item is defined
      with_items:
        - ambiente
        - sito

    - name: Loading {{ ambiente }} Environment Settings for Site {{ sito }}
      include_vars:
        dir: vars/{{ ambiente }}/{{ sito }}
        depth: 1

  tasks:

    - name: query database
      ari_stark.ansible_oracle_modules.oracle_sql:
        hostname: "oradb19c.betatest.local"
        username: "mgmt"
        password: "8volante"
        service_name: "OMUVF"
        sql: "select * from hosts"
      register: sqlout

    - debug:
        var: sqlout.data

