
- name: test collections playbook
  hosts: localhost
  collections:
    - community.mysql
  connection: local
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

    - name: test mysql collection
      community.mysql.mysql_query:
        login_db: prova
        query: select * from hosts
      ignore_errors: true

