
- name: test collections playbook
  hosts: localhost
  collections:
    - community.mysql
  connection: local
  gather_facts: true

  tasks:

    - name: test mysql collection
      community.mysql.mysql_query:
        login_db: prova
        query: select * from hosts
      delegate_to: localhost
      run_once: true
      ignore_errors: true

