
- name: "ISP {{ ambiente }} Environment DR Switch to {{ sito }} Site - test parallel"
  hosts: all
  gather_facts: false

  pre_tasks:

    - assert:
        that: item is defined
      with_items:
        - ambiente
        - sito
      delegate_to: localhost
      run_once: true

    - name: Loading {{ ambiente }} Environment Settings for Site {{ sito }}
      include_vars: 
        dir: vars/{{ ambiente }}/{{ sito }}
        depth: 1
      delegate_to: localhost
      run_once: true

  tasks:

    - name: write files
      shell: date +"%T.%N" > /tmp/ans_test_parallel.txt
      when: inventory_hostname in linux_servers
      #when: inventory_hostname == 'omlbgt.betatest.local' or inventory_hostname == 'omlagt.betatest.local'

